### ISSUE TITLE
does not work for a file call article.router.ts

### ISSUE THREAD

**Issue by jlguenego** [barhun/extensionless#1]
Thanks for this very useful module.

My issue: 
It works for the file `articleRouter.ts` but not for `article.router.ts`.

I think you should reenforce the pattern where you add the js extension or not.

**Comment by barhun** [comment]
Fixed and pushed a new package to `npm`. Could you try with version `1.1.1`?

**Comment by jlguenego** [comment]
well done 👍 🥇 😊
