### ISSUE TITLE
Also handle imports deep imports from libraries?

### ISSUE THREAD

**Issue by CarsonF** [barhun/extensionless#2]
This might be my missing link to actually adopt ESM, so thank you for that.

I'm wondering if you think it's possible to also handle library imports. Something like
```ts
import { isPlainObject } from '@nestjs/common/utils/shared.utils';
```
Adding the extension to that import fixes it.
Maybe that's harder though logically, because there's package.json `exports` to consider. Or some other complication with non-local code?

**Comment by barhun** [comment]
I think it's better to not modify the default package resolution behavior for the reasons mentioned below:

[Why deep imports can be a problem](https://gist.github.com/daleyjem/0f38f561a4e91e58eba580889f38330f#why-deep-imports-can-be-a-problem)

[Deep imports for dual packages presents a problem for transpiling for dual-packages](https://github.com/nodejs/modules/issues/352)

**Comment by CarsonF** [comment]
Yeah makes sense 👍

**Comment by barhun** [comment]
Have you considered using [subpath imports](https://nodejs.org/api/packages.html#subpath-imports) instead?

**Comment by CarsonF** [comment]
Was not aware of that. Good to know. But many of these imports are only done once, so a separate mapping isn't worth it.

**Comment by barhun** [comment]
You might wanna give it a try with the latest version of the npm package. (:
