### ISSUE TITLE
imports `#xxx` specifiers should be always resolved locally

### ISSUE THREAD

**Issue by hax** [barhun/extensionless#6]
nodejs package.json imports field support `#xxx` specifier, which should be always resolved locally. 

eg. package "a" has dep "b", both have `imports` field in their package.json: `imports: { "#foo": "./foo.js" }`. In the "b" package there is a file contains `import "#foo"` which should be resolved to `b/foo.js`, but currently it will be resolved to `a/foo.js`.

**Comment by barhun** [comment]
I think it's a better choice to leave alias resolution completely to the default ESM resolver of the node.js, so I've removed the part handling aliases and published a new package to the npm as  `1.9.7`, can you test your project setup with this new version?

**Comment by hax** [comment]
I think it works now, thank you.
